### PR TITLE
feat: Fix skeleton bug + Add new monsters for v1.5

### LINKED ISSUE #3: Skeleton spawn not working
This shows up in SMAPI
[game] An error occurred in the base update loop: System.MissingMethodException: Constructor on type 'StardewValley.Monsters.Skeleton' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Spawn_Monsters.MonsterSpawning.Spawner.SpawnMonster(Monster monster, Vector2 location) in E:\Programming\GitHub\SpawnMonsters\Spawn Monsters\MonsterSpawning\Spawner.cs:line 61
   at Spawn_Monsters.MonsterPlaceMenu.receiveLeftClick(Int32 x, Int32 y, Boolean playSound) in E:\Programming\GitHub\SpawnMonsters\Spawn Monsters\MonsterMenu\MonsterPlaceMenu.cs:line 53
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 5240
   at StardewValley.Game1._update(GameTime gameTime) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 4574
   at StardewValley.Game1.Update(GameTime gameTime) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 3757
   at StardewModdingAPI.Framework.SGame.<>c__DisplayClass35_0.<Update>b__0() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 169
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 987

### PR DESCRIPTION
**Pull request by PotatotatoCode**
Changes:
- Fixes #3 
- Adds monsters from the v1.5 patch
  - And adds them to monster_list
  - And moves monster_list out to a new class
- Increase height of menu to accommodate all of the new monsters

### CODE REVIEW

**Comment by PotatotatoCode** [comment]
Leave me alone better code hub

**Comment by Berisan** [comment]
Uhm yeah I removed it for now lol

Thank you for this, will take a look later

**Comment by PotatotatoCode** [comment]
> Uhm yeah I removed it for now lol
> 
> Thank you for this, will take a look later

No rush and thank you for creating this useful mod in the first place! I just figured if I was going to make these changes for my own use, I might as well make it available for others too.

**Comment by Berisan** [comment]
Looks good, thanks again!

**Pull request merged**
